language: groovy
jdk:
- oraclejdk8
sudo: false
branches:
  only:
  - master
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - secure: SBSBEZAz2/z+RgA8SRAWYjHtATb5cPaL6VIZn35DsupX9Wy/NvEeIq6JDz74Akml5Zdr4Z8lVUrX8GdlVcGACqd4W7wneF3VhzxrKlq02Sr3bO1UXaNzVKE5NwAVO9gVaPEZ4sf8/JKQ70SrVpB1KF+Ebdm8nlZWPtlp/yyuy8Sm83ON32nxT/dMDNHETem9j6akDW+QhpxdHDdFRK+e70tgiRdbDWS9kUM9Ghp3X+i5zyTHVUY5vWZHoy10okNrZxtDkiaCPIdWoc+hEaaHBFQxADOAxOWAVk/nfh616ef+/w/ayPUcBgCrZwck7LV3gSKBnBOJxxRr8cSbzQ4rZ+tSuUEvq7IWjf7gTn0Rcyft1y/VDmN1Y00lId4EZ1XLMTcQX+l+GSdiooKQBIV/ZP9aajceiq+56giI5fJGsoFKMMFxxUHk3LgVMaFnvszk/3JfG8WfEE1DbgbanflO8wiA/m+5/yA4f2LwSahnWKdapHeYjJUdP0/1WWWpyPHiXCFKnjmUl00C28k+4LJkPbwy3ydb3SZBj5jhUYInQwDJBvu7vqo8qib6TlvP1OR0EBs69/gUQM3rh+I664XGgnktFjDxOnrZjBMY/f3oW6U90gNQfIdxz8JrdboAlas180qsNCKhPKMX+ILAhJWWbhsjGe6t9UCVwtwz0VpxJ78=
  - secure: ZU/dI1JI/UKYa8iy2OKG1DsjbVvNB5wNnPqNjg6591z/d4cNJxgLADvscu2R/NqQYvIb6zdHleY6XIw6bCykYSanT45ImVdI2vr6OU3OmADZd/4VqIsQhIrgaG3Z/J8/MIseGd+LDNMEONH6mVjBg5lKKPvNkDyYbPS8Q1dMLNHnYHmMJyeY68dvWW4m8B8cvvB+yOiLVCwpMO5qD9dLfJijKkTc5wOCyy5YlwtC7AyTmt7lQ8Nbj1wBOdKYkdzPccfLEsIv2VwOPLwJH5vgBbkokXIfdfEdVQHEQqS0eiePZ2dia9EnB7CnThIEvVKK/kg6Aq4NRBC56IED4jv37eOynWxFd6jcn6J0xGToBcxo0edRWg4np3FY+SLOCzMLBtZpYoqYegxevaJkeK+6a/lSFyMuoO7UDGNbg+j8vHbrT07mwvJg2tI27kYr1fKfIvyl+4Vf4iF5Lgqp7GD5NV0wne6obFPMjaZWVZgnhhv6NowaKUHEI3VsDujqlNhaLKoPRPRYTW8k+vQu9wj7DItPWtddjqgFRB0TjTfIcvn+XudwY1cC2hvok7byKac3vjPv5XM87tqfjYwV7PHDWw0Ll1X8u1QRkjK0UbhbDyRyxgn2bQx80/ImbIKgvRLi8AW+QW/L3vu4I+a9QfCCdqaTc8Xo2T3ab2CSCz+wMt0=
